#!/usr/bin/env python3

# Copyright 2020 Mike Iacovacci
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from lib.functions import *


def main():

    try:
        settings = get_args()

        validate_privileges(settings.get("mode"))

        if settings.get("mode") == "init":
            initialize(settings)

        setup_folders(settings)

        if settings.get("mode") == "reload":
            reload()

        inventory = load_inventory()
        tool_list = load_tool_list(inventory)
        tool_names = get_tool_names(tool_list)
        tools = load_tools(inventory, tool_list[:])

        branch(settings, tool_list, tools)

        print_stats(inventory, tool_list, tools)
        print_banner(config.axiom.banner_file)

        exit_code = axiom_prompt(tool_list, tool_names, tools)

        print("Exiting...")
        exit(exit_code)

    except KeyboardInterrupt:
        print_error("Keyboard interrupt received")
        return 1


if __name__ == '__main__':
    main()

